-- Products
INSERT INTO products (name, brand, category, description, price, bpom_number, bpom_verified, active_ingredients) VALUES
('Acne Care Face Wash', 'Wardah', 'cleanser', 'Facial wash khusus untuk kulit berjerawat dengan Tea Tree Oil', 35000, 'NA18201200345', 1, 'Tea Tree Oil, Salicylic Acid'),
('Perfect Bright Micellar Water', 'Wardah', 'cleanser', 'Micellar water yang membersihkan dan mencerahkan kulit', 42000, 'NA18201200456', 1, 'Niacinamide, Vitamin C'),
('Holyshield! Sunscreen Serum', 'Somethinc', 'sunscreen', 'Sunscreen SPF 50 PA++++ dengan tekstur ringan', 89000, 'NA18211234567', 1, 'SPF 50, Hyaluronic Acid, Niacinamide'),
('Niacinamide + Moisture Beet Serum', 'Somethinc', 'serum', 'Serum untuk mencerahkan dan melembabkan kulit', 119000, 'NA18211234568', 1, 'Niacinamide 5%, Beetroot Extract'),
('Miraculous Retinol Serum', 'Avoskin', 'serum', 'Serum anti-aging dengan Retinol untuk memperbaiki tekstur kulit', 179000, 'NA18201300123', 1, 'Retinol, Hyaluronic Acid, Vitamin E'),
('Hydrating Treatment Essence', 'Avoskin', 'toner', 'Essence untuk hidrasi intensif dan mencerahkan', 139000, 'NA18201300124', 1, 'Niacinamide, Ceramide, Hyaluronic Acid'),
('10% Niacinamide Brightening Serum', 'Skintific', 'serum', 'Serum brightening dengan konsentrasi Niacinamide tinggi', 149000, 'NA18221234789', 1, 'Niacinamide 10%, Alpha Arbutin, Vitamin B5'),
('MSH Niacinamide Brightening Moisture Gel', 'Skintific', 'moisturizer', 'Moisturizer gel ringan dengan MSH technology', 98000, 'NA18221234790', 1, 'Niacinamide, MSH, Ceramide'),
('Acne Spot Treatment Gel', 'Elsheskin', 'serum', 'Treatment khusus untuk jerawat membandel', 125000, 'NA18191200234', 1, 'Salicylic Acid, Tea Tree, Centella'),
('Hydra Bright AHA BHA PHA Toner', 'Elsheskin', 'toner', 'Toner exfoliating untuk kulit lebih cerah', 89000, 'NA18191200235', 1, 'AHA, BHA, PHA, Niacinamide'),
('Barrier+ Ceramide Moisturizer', 'Avoskin', 'moisturizer', 'Moisturizer untuk memperbaiki skin barrier', 169000, 'NA18201300125', 1, 'Ceramide Complex, Centella, Hyaluronic Acid'),
('Calming Centella Toner', 'Somethinc', 'toner', 'Toner untuk menenangkan kulit sensitif dan kemerahan', 79000, 'NA18211234569', 1, 'Centella Asiatica, Panthenol, Allantoin'),
('Oil Control Face Wash', 'Wardah', 'cleanser', 'Pembersih wajah untuk mengontrol minyak berlebih', 28000, 'NA18201200457', 1, 'Witch Hazel, Tea Tree'),
('Hydra Bomb Sleeping Mask', 'Somethinc', 'mask', 'Sleeping mask untuk hidrasi maksimal semalam', 139000, 'NA18211234570', 1, 'Hyaluronic Acid, Ceramide, Peptide'),
('Clay Mask Purifying', 'Skintific', 'mask', 'Masker tanah liat untuk membersihkan pori-pori', 95000, 'NA18221234791', 1, 'Kaolin Clay, Charcoal, Tea Tree'),
('Gentle Exfoliating Scrub', 'Wardah', 'exfoliant', 'Scrub lembut untuk mengangkat sel kulit mati', 32000, 'NA18201200458', 1, 'Microbeads Alami, Vitamin E'),
('Glow Booster Vitamin C Serum', 'Avoskin', 'serum', 'Serum Vitamin C untuk kulit lebih glowing', 159000, 'NA18201300126', 1, 'Vitamin C 15%, Ferulic Acid, Vitamin E'),
('Lightweight Hydrating Lotion', 'Elsheskin', 'moisturizer', 'Pelembab ringan untuk kulit berminyak', 89000, 'NA18191200236', 1, 'Hyaluronic Acid, Niacinamide'),
('Clear Pore Clay Cleanser', 'Skintific', 'cleanser', 'Pembersih berbasis clay untuk pori-pori bersih', 68000, 'NA18221234792', 1, 'Bentonite Clay, Salicylic Acid, Tea Tree'),
('Soothing Aloe Vera Gel', 'Wardah', 'moisturizer', 'Gel aloe vera untuk menenangkan dan melembabkan', 25000, 'NA18201200459', 1, 'Aloe Vera 98%, Allantoin');

-- Product Reviews
INSERT INTO product_reviews (product_id, reviewer_name, rating, review_text) VALUES
(1, 'Siti Nurhaliza', 5, 'Bagus banget! Jerawat ku berkurang drastis setelah pakai ini rutin. Wajib coba!'),
(1, 'Rina Handayani', 4, 'Lumayan oke, tapi agak bikin kering di awal. Setelah cocok jadi bagus.'),
(1, 'Dea Ananda', 5, 'Harganya terjangkau dan hasilnya memuaskan. Jerawat cepat kempes.'),
(2, 'Putri Maharani', 5, 'Micellar water favorit! Bersih tuntas dan gak bikin perih.'),
(2, 'Lisa Kusuma', 4, 'Oke sih, tapi untuk makeup waterproof butuh usaha lebih.'),
(2, 'Maya Sari', 5, 'Cocok buat kulit sensitif. Wajah jadi lebih cerah juga.'),
(3, 'Ratna Dewi', 5, 'Sunscreen terbaik! Ringan, gak lengket, gak whitecast. Worth it banget!'),
(3, 'Ayu Lestari', 5, 'Ini holy grail sunscreen aku. Pakai tiap hari gak bikin jerawatan.'),
(3, 'Indah Permata', 4, 'Bagus tapi agak pricey. Tapi hasilnya sebanding sih.'),
(4, 'Sinta Wijaya', 5, 'Kulit jadi glowing dan lembab. Favorite serum aku sekarang!'),
(4, 'Nia Rahmawati', 4, 'Bagus tapi butuh waktu untuk lihat hasil cerahnya. Sabar ya!'),
(5, 'Diah Puspita', 5, 'Retinol yang gentle! Cocok untuk pemula. Tekstur kulit membaik.'),
(5, 'Mega Wulandari', 4, 'Hasilnya oke, tapi harus telaten pakai sunscreen pas siang.'),
(5, 'Lina Susanti', 5, 'Fine lines berkurang setelah 2 bulan pakai. Recommended!'),
(6, 'Yuni Kartika', 5, 'Essence yang hydrating banget. Kulit jadi kenyal dan cerah.'),
(6, 'Fitri Anggraini', 4, 'Bagus tapi botolnya cepet habis karena aku pakai banyak hehe.'),
(7, 'Rara Amalia', 5, 'Niacinamide 10% tapi gak bikin iritasi. Flek hitam memudar!'),
(7, 'Tari Purnama', 5, 'Cocok banget untuk kulit kusam. Hasilnya kelihatan cepet.'),
(7, 'Nina Cahaya', 4, 'Bagus tapi agak sticky di awal. Setelah meresap oke sih.'),
(8, 'Bella Pratiwi', 5, 'Gel moisturizer yang perfect! Ringan, cepat meresap, melembabkan.'),
(8, 'Citra Melati', 5, 'Cocok buat kulit berminyak. Gak bikin minyakan tapi tetap lembab.'),
(9, 'Wulan Safitri', 4, 'Lumayan ampuh untuk jerawat yang baru muncul. Cepet kempes.'),
(9, 'Dewi Laksmi', 5, 'Spot treatment terbaik! Jerawat cystic aku jadi lebih kecil.'),
(10, 'Amel Kuswardani', 5, 'Toner exfoliating yang gentle. Kulit jadi halus dan cerah.'),
(10, 'Rini Marlina', 4, 'Bagus tapi jangan keseringan pakai, bisa over-exfoliate.'),
(11, 'Dinda Safira', 5, 'Moisturizer terbaik untuk repair skin barrier. Game changer!'),
(11, 'Vina Ratnasari', 5, 'Kulitku yang sensitif jadi lebih tenang pakai ini. Love it!'),
(12, 'Sari Mulyani', 5, 'Centella toner yang menenangkan banget. Kemerahan hilang!'),
(12, 'Laras Pramesti', 4, 'Bagus untuk kulit sensitif, tapi hasilnya butuh waktu.'),
(13, 'Tika Wahyuni', 4, 'Face wash yang oke untuk kulit berminyak. Tapi agak drying.'),
(13, 'Eka Novita', 5, 'Minyak terkontrol seharian. Harga juga ramah kantong!'),
(14, 'Putri Ayu', 5, 'Sleeping mask yang bikin bangun pagi langsung glowing!'),
(14, 'Nisa Amira', 5, 'Hidrasi maksimal! Kulit jadi kenyal dan lembut banget.'),
(15, 'Yuli Setiawan', 4, 'Clay mask yang bagus untuk deep cleansing. Pori-pori bersih.'),
(15, 'Mira Cahyani', 5, 'Komedo terangkat! Pakai seminggu sekali hasilnya oke.'),
(16, 'Dwi Lestari', 4, 'Scrub yang lembut, gak bikin iritasi. Kulit jadi halus.'),
(16, 'Rina Susilawati', 3, 'Lumayan oke, tapi mungkin butuh yang lebih exfoliating.'),
(17, 'Anisa Putri', 5, 'Vitamin C serum yang gak bikin breakout. Kulit cerah natural!'),
(17, 'Desi Rahmawati', 4, 'Bagus tapi harus disimpan di kulkas biar gak cepet oksidasi.'),
(18, 'Winda Lestari', 5, 'Pelembab ringan yang cocok untuk iklim tropis. Gak gerah!'),
(18, 'Lia Permatasari', 4, 'Oke untuk pagi hari, tapi kurang untuk malam.'),
(19, 'Tina Wulandari', 5, 'Clay cleanser yang bersih banget! Kulit jadi matte.'),
(19, 'Ratih Kusuma', 4, 'Bagus tapi jangan pakai terlalu sering, bisa kering.'),
(20, 'Siska Handayani', 5, 'Aloe vera gel yang multifungsi. Harga super terjangkau!'),
(20, 'Nana Suryani', 5, 'Cocok untuk kulit sensitif dan sunburn. Must have!');

-- Skincare Routines
INSERT INTO skincare_routines (condition_type, step_number, step_title, step_description) VALUES
-- Jerawat
('jerawat', 1, 'Bersihkan wajah 2x sehari', 'Gunakan cleanser khusus jerawat dengan salicylic acid atau tea tree oil. Bersihkan dengan lembut, jangan digosok keras.'),
('jerawat', 2, 'Gunakan toner exfoliating', 'Pakai toner dengan AHA/BHA untuk membantu mengangkat sel kulit mati dan mencegah pori-pori tersumbat.'),
('jerawat', 3, 'Aplikasikan spot treatment', 'Oleskan gel anti-jerawat langsung pada jerawat yang meradang. Biarkan meresap sebelum lanjut ke step berikutnya.'),
('jerawat', 4, 'Pakai moisturizer ringan', 'Pilih pelembab berbasis gel atau lotion yang oil-free agar tidak menyumbat pori-pori.'),
('jerawat', 5, 'Sunscreen wajib di pagi hari', 'Gunakan sunscreen minimal SPF 30 untuk melindungi kulit dari UV yang bisa memperparah bekas jerawat.'),
-- Berminyak
('berminyak', 1, 'Cuci wajah dengan oil control cleanser', 'Bersihkan wajah 2x sehari dengan pembersih yang mengontrol minyak berlebih. Jangan terlalu sering mencuci karena bisa trigger produksi minyak lebih banyak.'),
('berminyak', 2, 'Pakai toner mattifying', 'Gunakan toner yang membantu menyeimbangkan pH kulit dan mengontrol sebum.'),
('berminyak', 3, 'Aplikasikan serum niacinamide', 'Niacinamide membantu mengecilkan pori-pori dan mengontrol produksi minyak berlebih.'),
('berminyak', 4, 'Moisturizer gel ringan', 'Kulit berminyak tetap butuh hidrasi! Pilih moisturizer berbasis gel yang cepat meresap.'),
('berminyak', 5, 'Sunscreen matte finish', 'Pilih sunscreen dengan tekstur matte atau gel untuk menghindari kilap berlebihan.'),
('berminyak', 6, 'Masker clay 1-2x seminggu', 'Gunakan clay mask untuk deep cleansing dan menyerap minyak berlebih.'),
-- Kering
('kering', 1, 'Gunakan gentle cleanser', 'Pilih pembersih yang lembut dan melembabkan. Hindari cleanser yang mengandung alkohol atau sulfate keras.'),
('kering', 2, 'Pakai hydrating toner/essence', 'Aplikasikan essence atau toner yang hydrating untuk mengembalikan kelembaban kulit.'),
('kering', 3, 'Layer serum hyaluronic acid', 'Hyaluronic acid membantu menarik dan mengunci kelembaban di kulit.'),
('kering', 4, 'Gunakan moisturizer kaya', 'Pilih moisturizer dengan tekstur krim yang mengandung ceramide untuk memperbaiki skin barrier.'),
('kering', 5, 'Aplikasikan facial oil (opsional)', 'Tambahkan facial oil di malam hari untuk extra nourishment pada kulit sangat kering.'),
('kering', 6, 'Sunscreen melembabkan', 'Gunakan sunscreen yang juga memberikan hidrasi ekstra.'),
('kering', 7, 'Pakai sleeping mask', 'Gunakan sleeping mask 2-3x seminggu untuk hidrasi intensif overnight.'),
-- Kusam
('kusam', 1, 'Exfoliate rutin', 'Gunakan gentle exfoliant 2-3x seminggu untuk mengangkat sel kulit mati yang membuat kulit kusam.'),
('kusam', 2, 'Cleanser brightening', 'Pilih pembersih dengan bahan brightening seperti vitamin C atau niacinamide.'),
('kusam', 3, 'Toner dengan AHA/BHA', 'Gunakan chemical exfoliant untuk membantu regenerasi sel kulit lebih cepat.'),
('kusam', 4, 'Serum vitamin C atau niacinamide', 'Aplikasikan serum brightening untuk mencerahkan dan meratakan warna kulit.'),
('kusam', 5, 'Moisturizer dengan brightening agent', 'Gunakan pelembab yang juga mengandung bahan pencerah.'),
('kusam', 6, 'Sunscreen setiap hari', 'SPF adalah kunci mencegah kusam karena paparan UV. Wajib pakai setiap hari!'),
('kusam', 7, 'Masker brightening 2x seminggu', 'Gunakan sheet mask atau wash-off mask untuk boost kecerahan.'),
-- Kemerahan
('kemerahan', 1, 'Gunakan gentle cleanser', 'Pilih pembersih yang sangat lembut dan tidak mengandung fragrance untuk menghindari iritasi.'),
('kemerahan', 2, 'Pakai calming toner', 'Gunakan toner dengan centella, chamomile, atau aloe vera untuk menenangkan kulit.'),
('kemerahan', 3, 'Serum anti-inflammatory', 'Aplikasikan serum dengan bahan calming seperti centella asiatica, niacinamide, atau azelaic acid.'),
('kemerahan', 4, 'Moisturizer untuk kulit sensitif', 'Pilih pelembab yang hypoallergenic dan free dari fragrance serta pewarna.'),
('kemerahan', 5, 'Sunscreen physical/mineral', 'Gunakan sunscreen berbasis zinc oxide atau titanium dioxide yang lebih gentle untuk kulit sensitif.'),
('kemerahan', 6, 'Hindari pemicu iritasi', 'Hindari produk dengan alkohol, fragrance, essential oil, dan scrub kasar.'),
('kemerahan', 7, 'Kompres dingin jika perlu', 'Gunakan kompres dingin untuk meredakan kemerahan yang sedang meradang.'),
-- Kombinasi
('kombinasi', 1, 'Bersihkan dengan balanced cleanser', 'Gunakan pembersih yang gentle tapi efektif membersihkan, tidak terlalu stripping.'),
('kombinasi', 2, 'Toner seimbang', 'Pakai toner yang hydrating tapi tidak terlalu berat, bisa dengan niacinamide.'),
('kombinasi', 3, 'Serum targeted', 'Aplikasikan serum sesuai kebutuhan area wajah (contoh: salicylic acid di T-zone, hyaluronic acid di pipi).'),
('kombinasi', 4, 'Moisturizer gel-cream', 'Pilih tekstur yang medium, bisa gel-cream hybrid yang melembabkan tanpa membuat berminyak.'),
('kombinasi', 5, 'Sunscreen hybrid', 'Gunakan sunscreen yang nyaman dan tidak membuat T-zone terlalu oily.'),
('kombinasi', 6, 'Multi-masking', 'Gunakan clay mask di T-zone dan hydrating mask di area kering saat maskeran.'),
('kombinasi', 7, 'Sesuaikan produk per area', 'Jangan takut menggunakan produk berbeda untuk zona berbeda di wajah.');
